### ISSUE TITLE
Unknown Syntax Error: Unsupported option name ("--loglevel").

### ISSUE THREAD

**Issue by JonasKuschel** [remix-pwa/remix-pwa#108]
I am trying to install the pwa in my typescript installation. I use yarn. I get an Unsupported option name ("--loglevel") error.

Also I have the error in #107 

Help is appreciated! 🙏🏻

npx remix-pwa@latest --ts  --install         
Welcome to Remix PWA!

✔ What features of remix-pwa do you need? Don't be afraid to pick all! · Service Workers, Web Manifest, Push Notifications

✔ What caching strategy do you want to use? Check out the docs for more info. · Precaching
✔ Do you want to use Workbox? (y/N) · false
✔ What is the location of your Remix app? · app

PWA Service workers successfully integrated into Remix! Check out the docs for additional info.

Running postinstall scripts....
Successfully ran postinstall scripts!
Running yarn install....
Unknown Syntax Error: Unsupported option name ("--loglevel").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
Error: Command failed: yarn install --loglevel silent
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Setup (/Users/jonaskuschel/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:190:9)
    at async cli (/Users/jonaskuschel/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:484:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7880,
  stdout: null,
  stderr: null
}

**Comment by ShafSpecs** [comment]
👋 Thanks for opening an issue @JonasKuschel 

The issue is a minor one caused by Yarn (and us). Would provide a patch later this evening, the problem is due to running `--loglevel` to keep all of npm messages off (but this isn't npm)

**Comment by ShafSpecs** [comment]
*Published fixes*
