### ISSUE TITLE
`PrecacheHandler` Bug

### ISSUE THREAD

**Issue by jmaldon1** [remix-pwa/remix-pwa#110]
Seems like this function is wrong:

```
function getPathname(route: EntryRoute) {
      if (route.index) return '/';

      let pathname = '';
      if (route.path && route.path.length > 0) {
        pathname = '/' + route.path;
      }
      if (route.parentId) {
        const parentPath = getPathname(manifest.routes[route.parentId]);
        if (parentPath) {
          pathname = parentPath + pathname;
        }
      }
      return pathname;
    }
```
I am getting many errors similar to this:

`entry.workbox.js:1963 remix-pwa Failed to cache data for /?_data=routes%2Fdashboard._index: TypeError: Failed to execute 'add' on 'Cache': Request failed`

and it seems like you are checking if a route has `.index` and then defaulting to `/`. Many routes can end in `._index` and they have nothing to do with the `/` route.

Also it was hard to know where all these errors were coming from without a bunch of commenting out, trial and error. Is it possible to put more logging that explains that this is the precaching section that is within the `self.addEventListener("message", (event: ExtendableMessageEvent)` callback

**Comment by jmaldon1** [comment]
Also i have some routes that do the following in the loader:

```tsx
export const loader = async (_: LoaderArgs): Promise<never> => {
  throw new Response("Not Found", {
    status: 404,
  });
};
```

Because I use them in a special way, there may need to be a way to exclude files from the precache.

**Comment by ShafSpecs** [comment]
> Because they are not meant to be accessed with a GET request. So is there a way to exclude files from the precache step. Preferably by REGEX because I have many with similiar patterns.

Currently, nope. But thanks for the suggestion, would definitely look into that. The roadmap (which I am super lazy [and busy] to update) next important thing is to actually give more control to the devs over the handlers and what's possible, etc.

**Comment by ShafSpecs** [comment]
> Also it was hard to know where all these errors were coming from without a bunch of commenting out, trial and error. Is it possible to put more logging that explains that this is the precaching section that is within the `self.addEventListener("message", (event: ExtendableMessageEvent)` callback

Yes, entirely possible! Would just require me to add more `logger`s to the code (that can be turned off) so that every step is monitored successfully.

**Comment by ShafSpecs** [comment]
@dev-afzalansari Is this something you could maybe explore a bit when you are less busy? Pretty please.

**Comment by dev-afzalansari** [comment]
Yeah sure, It may take a while but hopefully I will get it to it.

**Comment by ShafSpecs** [comment]
<img width="621" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/69679506/ed84cc43-fc03-4189-9fd3-b622050558c9">

@jmaldon1 Providing an ignored routes option to precache handler, any other thing you would probably like to see in the new update?

**Comment by ShafSpecs** [comment]
> I am getting many errors similar to this:
> 
> `entry.workbox.js:1963 remix-pwa Failed to cache data for /?_data=routes%2Fdashboard._index: TypeError: Failed to  execute 'add' on 'Cache': Request failed`

By chance, do these routes throw errors in their loaders? or return an response of code 500?

**Comment by jmaldon1** [comment]
> <img alt="image" width="621" src="https://user-images.githubusercontent.com/69679506/255425626-ed84cc43-fc03-4189-9fd3-b622050558c9.png">
> @jmaldon1 Providing an ignored routes option to precache handler, any other thing you would probably like to see in the new update, for the precache handler that is?

Sounds good, hopefully it can take REGEX strings so you can ignore many at a time.

**Comment by jmaldon1** [comment]
> > I am getting many errors similar to this:
> > `entry.workbox.js:1963 remix-pwa Failed to cache data for /?_data=routes%2Fdashboard._index: TypeError: Failed to  execute 'add' on 'Cache': Request failed`
> 
> By chance, do these routes throw errors in their loaders? or return an response of code 500?

They don't throw errors, the issue is that the route is `/dashboard?_data=routes%2Fdashboard._index` not `/?_data=routes%2Fdashboard._index`

**Comment by ShafSpecs** [comment]
> > <img alt="image" width="621" src="https://user-images.githubusercontent.com/69679506/255425626-ed84cc43-fc03-4189-9fd3-b622050558c9.png">
> > @jmaldon1 Providing an ignored routes option to precache handler, any other thing you would probably like to see in the new update, for the precache handler that is?
> 
> Sounds good, hopefully it can take REGEX strings so you can ignore many at a time.

```ts
export interface PrecacheHandlerState {
  ignoredRoutes?:
    | RegExp[]
    | string[]
    | ((route: EntryRoute) => boolean)[]
    | ((route: EntryRoute) => boolean)
    | null;
}
```

**Comment by ShafSpecs** [comment]
> /dashboard?_data=routes%2Fdashboard._index

@jmaldon1  Trying to replicate it, I have multiple test routes with loaders that return different things. Namely:
- `/`
- `/bar`
- `/foo`
- `/catch` - Returns a `Response` object with `null` and a status of 500
- `/error` - Throws an `Error`
- `/parent` 
- `/parent._index`
- `/parent/child`

Currently, the error throws for only that `catch` and `error` routes (still trying to understand why that happens). Btw, all the routes are cached including `catch` and `error` (I clear storage on each re-run).

**Comment by ShafSpecs** [comment]
@jmaldon1 Would push a patch soon to address just the PrecacheHandler issue, apparently, the error is triggered if the response code isn't a 200. In my case, I ignored the error routes and the errors were gone

<img width="500" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/69679506/7f52bf7b-2a5a-4143-bab0-11ffd0a9ee1a">

**Comment by jmaldon1** [comment]
Ah yeah so i have a `return redirect(`/dashboard/x`);` in the loader of `dashboard._index.tsx`. That could be why

**Comment by jmaldon1** [comment]
I thought the issue was that if the route was had `._index` on it, you were doing the following:

```tsx
function getPathname(route: EntryRoute) {
      if (route.index) return '/';
     .....
```

And then trying to cache the `/` route with `?_data=routes%2Fdashboard._index`. when instead you should be caching `/dashboard?_data=routes%2Fdashboard._index`.

**Comment by ShafSpecs** [comment]
@jmaldon1 Fixed the path name function too. It should work as expected in the next update (hopefully tomorrow, if I don't sleep in)

**Comment by ShafSpecs** [comment]
@dev-afzalansari Got a possible fix https://github.com/remix-pwa/sw/pull/22. 🙏

**Comment by ShafSpecs** [comment]
@jmaldon1 Fixed and added a new feature, docs update rolling out somewhile later. In the meantime, the new changes goes as thus:

```ts
const precacheHandler = new PrecacheHandler(
 assetCacheName: string,
 dataCacheName: string,
 documentCacheName: string,
 state: {
  ignoredRoutes?: RegExp[] | string[] | ((route: EntryRoute) => boolean)[] | ((route: EntryRoute) => boolean) | null;
  }
 }
)
