### ISSUE TITLE
Question - Loaders called multiple times

### ISSUE THREAD

**Issue by typytypytypy** [remix-pwa/remix-pwa#116]
I have a page that I only want the loader to be called once, so I have:
```
export const shouldRevalidate = () => false;
```
If I comment out `useSWEffect` and `loadServiceWorker` in root and entry.client (respectively) and refresh my page, it indeed, only calls the loader once. 

When I use PWA, and refresh the page, the loader is called multiple times. Why would this be the case?  

There are a couple of GET and POST requests going on after the page loads, but I wouldn't expect these to be causing the loader to re-run (which also adds load onto my DB)

**Comment by ShafSpecs** [comment]
@typytypytypy Are you using `StrictMode` in your `entry.client` file? `useSWEffect` utilises a `useEffect` hook under the hood. And `StrictMode` has a side effect that effects run twice. Try commenting it out and see if it is fixed 👍

**Comment by typytypytypy** [comment]
Thank you @ShafSpecs!  It's late here but I tested quickly and I think that's it!  I appreciate your help!

**Comment by vahidvdn** [comment]
Hi @ShafSpecs 
It was happening to me as well. When I have `StrictMode`  it calls loader 6 times, and when I remove `StrictMode` it calls 4 times.

It only gets fixed when I remove `useSWEffect`. Any idea?

**Comment by ShafSpecs** [comment]
> Hi @ShafSpecs 
> It was happening to me as well. When I have `StrictMode`  it calls loader 6 times, and when I remove `StrictMode` it calls 4 times.
> 
> It only gets fixed when I remove `useSWEffect`. Any idea?

Hmm, useSWEffect does revalidate on first load. I think I would pass in an option to disable it in the next version of sw package

**Comment by vahidvdn** [comment]
@ShafSpecs It doesn't matter, when you refresh the page from the browser, it always calls the loader 4 times.
But if you navigate from another page to that page, it only runs twice.

What happens if I completely remove `useSWEffect`?

**Comment by ShafSpecs** [comment]
> @ShafSpecs Yes, it gets fixed when I remove `useSWEffect`. For now I remove it. Please let me know if it's fixed in the next version

Kks. Would be removing that behavior on first reload then 👍
