### ISSUE TITLE
Module '"@remix-pwa/push"' has no exported member 'subscribeToPush'.

### ISSUE THREAD

**Issue by iChwn** [remix-pwa/remix-pwa#117]
When i'm trying to build my remix project then i caught an error like this

**Module '"@remix-pwa/push"' has no exported member 'subscribeToPush'.**

here is my build command

```javascript
"scripts": {
    "build": "concurrently \"npm run build:worker\" \"remix build\"",
    "dev": "concurrently  \"npm run compile:sass\" \"npm run dev:worker\" \"remix dev\"",
    "start": "remix-serve build",
    "typecheck": "tsc",
    "compile:sass": "sass --watch app/:app/",
    "build:worker": "esbuild ./app/entry.worker --outfile=./public/service-worker.js --minify --bundle --format=esm --platform=node --define:process.env.NODE_ENV='\"production\"'",
    "dev:worker": "esbuild ./app/entry.worker --outfile=./public/service-worker.js --bundle --format=esm --platform=node --define:process.env.NODE_ENV='\"development\"' --watch",
    "all": "concurrently  \"npm run compile:sass\" \"npm run dev:worker\" \"remix dev\""
  },
``` 

im using 
"@remix-pwa/push": "^1.0.1",
"@remix-pwa/sw": "^1.0.0",

how to fix this ?

**Comment by ShafSpecs** [comment]
@iChwn Can you please run `npm install @remix-pwa/push@1.0.0`? I have a feeling I messed something up in the latest patch

**Comment by iChwn** [comment]
![image](https://github.com/remix-pwa/remix-pwa/assets/29217999/d6234507-09c5-4d3a-aa56-ecbb71ee56dd)
Ithink the  @remix-pwa/push@1.0.0 is missing from package there's no v 1.0.0 in here
https://www.npmjs.com/package/@remix-pwa/push?activeTab=versions

**Comment by ShafSpecs** [comment]
Sorry, my bad. `1.0.2`

The current version is `1.0.3` so the last version would be `1.0.2`

**Comment by iChwn** [comment]
Ahh okay, it fix my issue. Thankyou!🎉

**Comment by ShafSpecs** [comment]
Awesome, I would revert the changes ASAP

**Comment by brianbolnick** [comment]
I am still seeing this issue on all imports from `@remix-pwa/push`, for what it's worth. I believe I'm on the latest of all packages (got upgraded to v3 today):

```
"@remix-pwa/cache": "^2.0.12",
"@remix-pwa/client": "^2.0.1",
"@remix-pwa/push": "^1.0.9",
"@remix-pwa/strategy": "^2.1.9",
"@remix-pwa/sw": "^2.1.11",
"@remix-pwa/sync": "^2.0.1",
"@remix-pwa/dev": "2.0.30",
"@remix-pwa/worker-runtime": "^2.0.7",
"remix-pwa": "^3.0.18",
```

Getting errors similar to this: 

```
✘ [ERROR] No matching export in "node_modules/@remix-pwa/push/lib/index.js" for import "subscribeToPush"

    app/components/someFile.tsx:5:9:
      5 │ import { subscribeToPush } from "@remix-pwa/push";
        ╵          ~~~~~~~~~~~~~~~
 ```
 
 Which makes me think the exports are still not setup properly (looks like it's missing one for `client` altogether):
 
 ```
 "exports": {
    ".": {
      "default": "./lib/index.js",
      "types": "./types/index.d.ts"
    },
    "./worker": {
      "default": "./lib/worker/index.js",
      "types": "./types/worker/index.d.ts"
    },
  },
```

For example, `import { Push } from "@remix-pwa/push/worker"` is not working either. Any thoughts?
