### ISSUE TITLE
Usage with typedjson + data (de)serialization

### ISSUE THREAD

**Issue by brianbolnick** [remix-pwa/remix-pwa#124]
Hi! I'm trying to set this up on our application that uses remix-typedjson. Since the data transfer is not serialized, the controller `postMessage` calls are all failing (on the `matches` key, specifically). Wondering what best practices are here or if there are any other creative ways to resolve this without rolling my own. Here's a screenshot of the console errors for reference (note: there are a few additional errors included here that I don't believe are related, but including for additional context):

<img width="521" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/4327477/5f2244c2-34ac-4d28-b73b-4cca8dd5a4d5">

TIA!

**Comment by ShafSpecs** [comment]
@brianbolnick Thank you for bringing this to our attention, do you mean you are using `remix-typedjson` in your loader calls and hence, it breaks when attempting to send data to the service worker (via `postMessage`)? I haven't looked at `remix-typedjson` APIs in depth but we had a sanitization function within the `useSWEffect` hook to avoid sending unserialized data. Oerhaps you could help me a bit here, is the data sent as a promise?

**Comment by brianbolnick** [comment]
Yes, it's ultimately a wrapper around `superjson` that prevents auto-deserializes inbound and outbound payloads for loaders and actions. It's a common practice to ensure end-to-end type safety. Think of it as a middleware that parses the response body as soon as it hydrates

**Comment by ShafSpecs** [comment]
I think the best solution would be to roll out your own implementation of `useSWEffect` hook, not too hard, you can use the original one here: https://github.com/remix-pwa/monorepo/blob/main/packages/sw/src/hooks/useSWEffect.ts as a template and replace the filtering/sanitization process with a more fitting one.

**Comment by ShafSpecs** [comment]
But still curious about this though, do you have a repro I can please use to test this out?

**Comment by brianbolnick** [comment]
You could check out the typedjson example repo, that's probably the easiest way to get something up and running that's similar to what we're doing https://github.com/kiliman/remix-typedjson-example

**Comment by brianbolnick** [comment]
Finally got around to this, got it working with a pretty simple workaround. Cloned the `useSWEffect` hook locally and added the following: 

```
    function deserializeRoute(route: RouteMatch) {
      return JSON.parse(JSON.stringify(route));
    }

...
        navigator.serviceWorker.controller?.postMessage({
          type: "REMIX_NAVIGATION",
          isMount: mounted,
          location,
          matches: matches
            .filter(filteredMatches)
            .map(deserializeRoute)
            .map(sanitizeHandleObject),
          manifest: window.__remixManifest,
        });

...

**Comment by ShafSpecs** [comment]
*Currently cleaning up issues and this issue has been deemed fixed for now*
