### ISSUE TITLE
All loadServiceWorker options are required

### ISSUE THREAD

**Issue by wKovacs64** [remix-pwa/remix-pwa#125]
I use a custom `workerName` in `remix.config.ts` (because this app has had a service worker prior to using Remix PWA and I'm under the impression I should keep the same name). As far as I can tell, this means I also need to configure the `serviceWorkerUrl` option when calling `loadServiceWorker`. The JSDoc comment for `loadServiceWorker` says "All parameters are optional." and I see they all have default values, but TypeScript is currently treating the options object as all-or-nothing and requiring I provide all the options rather than just `serviceWorkerUrl`.

I'm assuming the fields of the [`LoadServiceWorkerOptions`](https://github.com/remix-pwa/monorepo/blob/6fb95ac4cf6c242c31e377f763080cfbc279986e/packages/sw/src/react/loader.ts#L12) type just need changed to be optional?

**Comment by Sarabadu** [comment]
Yes you are right, those should be optional as they will use default values in any case,
Do you what to raise a PR for it?

**Comment by ShafSpecs** [comment]
Merged PR. Awaiting release (in a few hours, hopefully)

**Comment by ShafSpecs** [comment]
https://github.com/remix-pwa/monorepo/actions/runs/6408452460

Released
