### ISSUE TITLE
`remix-pwa build` process not exiting

### ISSUE THREAD

**Issue by wKovacs64** [remix-pwa/remix-pwa#126]
I just noticed `remix-pwa build` no longer exits after completing the build. Tested on both macOS and Windows. `@remix-pwa/dev@2.0.28` works as expected, so seems to be something in `@remix-pwa/dev@2.0.29`. Let me know if there's any other relevant information I can provide.

```
@remix-pwa/cache@2.0.11
@remix-pwa/strategy@2.1.8
@remix-pwa/sw@2.1.10
@remix-pwa/dev@2.0.29
@remix-pwa/worker-runtime@2.0.6
remix-pwa@3.0.17
```

Thanks.

P.S. Do you prefer issues logged here or on the monorepo?

**Comment by ShafSpecs** [comment]
> P.S. Do you prefer issues logged here or on the monorepo?

Any.

> I just noticed remix-pwa build no longer exits after completing the build. Tested on both macOS and Windows. @remix-pwa/dev@2.0.28 works as expected, so seems to be something in @remix-pwa/dev@2.0.29. Let me know if there's any other relevant information I can provide.

Interesting. Currently ill rn so can't debug before next week. But would look at it ASAP.

**Comment by ShafSpecs** [comment]
> > Interesting. Currently ill rn so can't debug before next week. But would look at it ASAP.
> 
> No worries. Feel better soon!

Thanks. Was able to look at it and as I guessed, wasn't a huge issue. I forgot to dispose the context after building (somehow, the tests passed that). Would be out soon enough

<img width="538" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/69679506/59016604-73e6-475d-b579-65e7506051c5">

**Comment by ShafSpecs** [comment]
Is it fixed now?

**Comment by wKovacs64** [comment]
> Is it fixed now?

Doesn't seem to be, at least on Windows with `@remix-pwa/dev@2.0.29-dev.2` and `@remix-pwa/worker-runtime@2.0.7-dev.1`. Tried to update the other packages too, but it looks like `@remix-pwa/sw@2.1.10-dev.2` has a peer dependency of `@remix-pwa/cache@^2.0.11-dev.3` which isn't published, so I couldn't try that combination.

**Comment by ShafSpecs** [comment]
> > Is it fixed now?
> 
> Doesn't seem to be, at least on Windows with `@remix-pwa/dev@2.0.29-dev.2` and `@remix-pwa/worker-runtime@2.0.7-dev.1`. Tried to update the other packages too, but it looks like `@remix-pwa/sw@2.1.10-dev.2` has a peer dependency of `@remix-pwa/cache@^2.0.11-dev.3` which isn't published, so I couldn't try that combination.

`remix-pwa@3.0.18` fixes this issue. Sorry for the inconvenience

**Comment by wKovacs64** [comment]
> `remix-pwa@3.0.18` fixes this issue. Sorry for the inconvenience

Confirmed. Thanks!
