### ISSUE TITLE
`npm start` fails

### ISSUE THREAD

**Issue by arpitdalal** [remix-pwa/remix-pwa#132]
Related to: #128
Hey @ShafSpecs, thanks for fixing the build issues 🎉 
But even after updating all the packages, after building the app, `npm start` fails and the generated `entry.worker.js` file has a bunch of errors in it. Here's the error I get with `npm start`:
```console
╰─ npm start                                                                                                              ─╯

> start
> cross-env NODE_ENV=production node .

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/mre-remix-pwa/node_modules/@remix-pwa/cache/node_modules/buffer/' is not supported resolving ES modules imported from /mre-remix-pwa/node_modules/@remix-pwa/cache/dist/src/cache.js
Did you mean to import buffer/index.js?
Error: Directory import '/mre-remix-pwa/node_modules/@remix-pwa/cache/node_modules/buffer/' is not supported resolving ES modules imported from /mre-remix-pwa/node_modules/@remix-pwa/cache/dist/src/cache.js
Did you mean to import buffer/index.js?
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:317:17)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
```
Here's the [MRE](https://github.com/arpitdalal/mre-remix-pwa/tree/remix-pwa)

**Comment by oliverborrie** [comment]
Seems like it is an issue with this line: https://github.com/remix-pwa/monorepo/blob/main/packages/cache/src/cache.ts#L1
Works if it is changed to `import * as B from 'buffer/index.js'`

**Comment by arpitdalal** [comment]
Yep, that's it! Here's a patch-package to fix it until the typo is fixed:
```
diff --git a/node_modules/@remix-pwa/cache/dist/src/cache.js b/node_modules/@remix-pwa/cache/dist/src/cache.js
index 2e2d4f5..7a29380 100644
--- a/node_modules/@remix-pwa/cache/dist/src/cache.js
+++ b/node_modules/@remix-pwa/cache/dist/src/cache.js
@@ -1,4 +1,4 @@
-import * as B from 'buffer/';
+import * as B from 'buffer';
 import { mergeHeaders, omit } from './utils.js';
 export var Strategy;
 (function (Strategy) {

```

**Comment by arpitdalal** [comment]
@ShafSpecs I've fixed the import, on which branch do you want me to make a PR?

**Comment by oliverborrie** [comment]
> Yep, that's it! Here's a patch-package to fix it until the typo is fixed:
> 
> ```
> diff --git a/node_modules/@remix-pwa/cache/dist/src/cache.js b/node_modules/@remix-pwa/cache/dist/src/cache.js
> index 2e2d4f5..7a29380 100644
> --- a/node_modules/@remix-pwa/cache/dist/src/cache.js
> +++ b/node_modules/@remix-pwa/cache/dist/src/cache.js
> @@ -1,4 +1,4 @@
> -import * as B from 'buffer/';
> +import * as B from 'buffer';
>  import { mergeHeaders, omit } from './utils.js';
>  export var Strategy;
>  (function (Strategy) {
> ```

That would cause it to import buffer from nodejs, the path is just in the incorrect format currently

**Comment by ShafSpecs** [comment]
*Closing issue as it's assumed to be solved*
