### ISSUE TITLE
useLocation() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by Fumaz** [remix-pwa/remix-pwa#133]
<img width="375" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/45318608/8ab53ec8-8b11-46cf-b433-7c325a4dba06">
<img width="518" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/45318608/b1e5baa8-579f-48d1-8995-ed0fcf710e0a">
<img width="367" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/45318608/a8eb5b21-3f1a-48f9-9848-9b0a2b085fd7">

**Comment by ShafSpecs** [comment]
@Fumaz Can't view the image you posted (Github images are broken), but this regularly occurs when you have two versions of remix in your application

**Comment by ShafSpecs** [comment]
@Fumaz has this issue been fixed. `@remix-pwa/sw` latest `1.x.x` version addressed this if I recall correctly. Which is caused by multiple versions of remix in your app (one in the package, one in your app)

**Comment by ShafSpecs** [comment]
*Closing, but not locking due to inactivity*
