### ISSUE TITLE
Usage with Vite

### ISSUE THREAD

**Issue by IgnisDa** [remix-pwa/remix-pwa#136]
Hello! Thanks for this project!

I would like to use this project with the vite compiler plugin that was launched recently (https://remix.run/docs/en/main/future/vite).

I followed all the instructions in the docs, but I get this error:

```
Internal server error: Directory import '/workspaces/ryot/apps/frontend/node_modules/buffer/'
 is not supported resolving ES modules imported from /workspaces/ryot/apps/frontend/node_modules/@remix-pwa/cac
he/dist/src/cache.js
Did you mean to import buffer/index.js?
```

**Comment by IgnisDa** [comment]
To add, I have already tried the solution in #129, it does not work.

**Comment by ShafSpecs** [comment]
@IgnisDa thanks for raising the issue. I am currently building a remix pwa vite plugin. The current solution is supposed to be for remix custom compilers and not vite

**Comment by IgnisDa** [comment]
@ShafSpecs thanks for the update! Is there any branch or PR that I can take a look at to track progress?

**Comment by ShafSpecs** [comment]
> @ShafSpecs thanks for the update! Is there any branch or PR that I can take a look at to track progress?

Yeah, haven't updated it in a while due to being ill 🤧. But checkout the feat/vite branch in the monorepo repo

**Comment by IgnisDa** [comment]
Thanks and get well soon!

**Comment by ShafSpecs** [comment]
Remix PWA + Vite PR
https://github.com/remix-pwa/monorepo/pull/124

**Comment by IgnisDa** [comment]
Hey @ShafSpecs, thanks for your work! Any updates on how far along this is?

**Comment by ShafSpecs** [comment]
> Hey @ShafSpecs, thanks for your work! Any updates on how far along this is?

Yeah, the PR comments indicate the current bugs and issues with Remix PWA + Vite. The main one now being worker loader/actions

**Comment by ShafSpecs** [comment]
Keeping mum about this for now, but Vite is currently being stabilized in Remix PWA. You can check it out here: https://github.com/remix-pwa/monorepo/tree/feat/stable-vite

Would be introducing an overhaul of how packages work, especially `dev` and runtimes as well as a new CLI system. That's all I would be leaking for now 🤫

**Comment by ShafSpecs** [comment]
Remix PWA v4 has been released :fire:. https://remix-pwa.run

Includes Vite stability and more
