### ISSUE TITLE
404 Broken Link to Docs Repo

### ISSUE THREAD

**Issue by charlesanim** [remix-pwa/remix-pwa#142]
Trying to access https://github.com/github.com/ShafSpecs/remix-pwa-docs from the contributing guide results in a 404. Please update the link to the docs repo as I’m trying to make a pr to fix some mini typos 🙏

**Comment by ShafSpecs** [comment]
> Trying to access https://github.com/github.com/ShafSpecs/remix-pwa-docs from the contributing guide results in a 404. Please update the link to the docs repo as I’m trying to make a pr to fix some mini typos 🙏

Oh, my bad! Could you please point out where exactly or open a PR? It's basically just me repeating `github.com` twice in the URL 🤦‍♂️

**Comment by ShafSpecs** [comment]
Updated docs already. Available at https://remix-pwa.run
