### ISSUE TITLE
null.querySelectorAll crash on the landing page

### ISSUE THREAD

**Issue by andremw** [remix-pwa/remix-pwa#144]
Hey guys, not sure if this is the best place to drop it, sorry if not.

I went to your [website](https://remix-pwa.run/), started reading, then went to Get Started and for some reason went back and then 💥 it crashed with this ugly error:

<img width="1728" alt="Screenshot 2024-03-27 at 07 38 08" src="https://github.com/remix-pwa/remix-pwa/assets/878746/b82d4d0f-4df9-4c70-a34e-115073336a8d">

It happens 100% of the time. To reproduce, just go to the landing page -> get started -> navigate back (browser's back, it doesn't happen if I click the logo on the top-left). If I refresh it renders the landing page normally.

**Comment by ShafSpecs** [comment]
> Hey guys, not sure if this is the best place to drop it, sorry if not.
> 
> I went to your [website](https://remix-pwa.run/), started reading, then went to Get Started and for some reason went back and then 💥 it crashed with this ugly error:
> 
> <img alt="Screenshot 2024-03-27 at 07 38 08" width="1728" src="https://private-user-images.githubusercontent.com/878746/317042794-b82d4d0f-4df9-4c70-a34e-115073336a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjIyMDAsIm5iZiI6MTcxMTYyMTkwMCwicGF0aCI6Ii84Nzg3NDYvMzE3MDQyNzk0LWI4MmQ0ZDBmLTRkZjktNGM3MC1hMzRlLTExNTA3MzMzNmE4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMDMxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDU5NjdkMzk3MDdmMDNjMzIxODI0NjczOTNhM2QxYmQ5MjcwY2U5NzdjN2VjNDk0MDFmOGNiYzNkMDQzMTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmE2HkUdTmos0-CsgsZR5gD_GR7dCOgpRiIfFosBPF4">
> It happens 100% of the time. To reproduce, just go to the landing page -> get started -> navigate back (browser's back, it doesn't happen if I click the logo on the top-left). If I refresh it renders the landing page normally.

Sorry I didn't respond, so I was actually re-writing the entire thing. Now available at: https://remix-pwa.run

And Remix PWA v4 has been releasede btw

**Comment by andremw** [comment]
Thanks, mate! Looks much cleaner! I'm excited to give it a go. Cheers,
