### ISSUE TITLE
npm ERR! 404  '@remix-pwa/push@^1.0.9' is not in this registry.

### ISSUE THREAD

**Issue by vahidvdn** [remix-pwa/remix-pwa#146]
This package was working before. Now when I removed my node_modules and package-lock.json, I get the following error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@remix-pwa%2fpush - Not found
npm ERR! 404 
npm ERR! 404  '@remix-pwa/push@^1.0.9' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vahid/.npm/_logs/2024-04-12T13_36_18_124Z-debug-0.log
```

These are my versions:

```json
"dependencies": {
  "@remix-pwa/cache": "^2.0.12",
  "@remix-pwa/client": "^2.0.1",
  "@remix-pwa/push": "^1.0.9",
  "@remix-pwa/strategy": "^2.1.9",
  "@remix-pwa/sw": "^2.1.12",
  "@remix-pwa/sync": "^2.0.1",
  "remix-pwa": "^3.0.19",
},
"devDependencies": {
    "@remix-pwa/dev": "2.0.31",
    "@remix-pwa/worker-runtime": "^2.0.8",
}
```

**Comment by vahidvdn** [comment]
@ShafSpecs Apparently the `@remix-pwa/push` is completely gone on npm:
https://www.npmjs.com/package/@remix-pwa/push?activeTab=readme

**Comment by ShafSpecs** [comment]
My bad, I deleted it last night. I'm re-writing the push as a whole to integrate into the new v4 ecosystem. What was meant to be a simple deprecation turned into a full blown deletion

**Comment by ShafSpecs** [comment]
I would try to republish, but it would be under a different name

**Comment by vahidvdn** [comment]
@ShafSpecs Then I would appreciate to inform me about the name, whenever it's done. Thank you

**Comment by ShafSpecs** [comment]
@vahidvdn Package now available at: https://www.npmjs.com/package/@remix-pwa/old-push

**Comment by vahidvdn** [comment]
Thanks @ShafSpecs 
Now I get this error:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@remix-pwa/client/-/client-2.0.2.tgz - Not found
```

**Comment by ShafSpecs** [comment]
> Thanks @ShafSpecs 
> Now I get this error:
> 
> ```
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@remix-pwa/client/-/client-2.0.2.tgz - Not found
> ```

Oh boy. Peer dependency issues. Would fix and republish soon

**Comment by ShafSpecs** [comment]
@vahidvdn Re-published the fix. Should be installable

**Comment by vahidvdn** [comment]
@ShafSpecs I'm still getting the same error. You can check this out by browser:

https://registry.npmjs.org/@remix-pwa/client/-/client-2.0.2.tgz

**Comment by vahidvdn** [comment]
@ShafSpecs This version worked fine: `"@remix-pwa/client": "^2.1.0-dev.1",`

**Comment by vahidvdn** [comment]
@ShafSpecs Now I can't build my app. I get the following error:

```
🏗️ Building Service Worker in development mode...

💿 Built Service Worker in: 8.599ms
👀 Watching for changes in the service worker file...
✘ [ERROR] Could not resolve "virtual:entry-sw"

    node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23:
      3 │ import * as build from 'virtual:entry-sw';
        ╵                        ~~~~~~~~~~~~~~~~~~

  You can mark the path "virtual:entry-sw" as external to exclude
  it from the bundle, which will remove this error and leave the
  unresolved path in the bundle.
```

**Comment by ShafSpecs** [comment]
@vahidvdn what are you installing? It's the push package you need right? That's available via: `@remix-pwa/old-push`

**Comment by vahidvdn** [comment]
@ShafSpecs Yes, it's fixed. Now I'm still getting the same error for `@remix-pwa/client"`. As I mentioned earlier, this version doesn't exist. You can also check with browser:

https://registry.npmjs.org/@remix-pwa/client/-/client-2.0.2.tgz

**Comment by ShafSpecs** [comment]
You would need the latest version for that 👍

**Comment by vahidvdn** [comment]
@ShafSpecs As I mentioned, the latest version is not working for me, because I don't want to upgrade to vite. For now, I just want to simply be able to build as before.

**Comment by ShafSpecs** [comment]
> @ShafSpecs As I mentioned, the latest version is not working for me, because I don't want to upgrade to vite. For now, I just want to simply be able to build as before. 

Oh, that's why. Didn't know that info. The new client should still work regardless though

**Comment by vahidvdn** [comment]
@ShafSpecs Sorry, but it doesn't. I'm getting these errors with new versions:

```
✘ [ERROR] Could not resolve "virtual:entry-sw"

    node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23:
      3 │ import * as build from 'virtual:entry-sw';
        ╵                        ~~~~~~~~~~~~~~~~~~

  You can mark the path "virtual:entry-sw" as external to exclude
  it from the bundle, which will remove this error and leave the
  unresolved path in the bundle.

/Users/vahid/casenio/dnw/dnw-ticketing/node_modules/esbuild/lib/main.js:1651
  let error = new Error(text);
```

**Comment by ShafSpecs** [comment]
> @ShafSpecs Now I can't build my app. I get the following error:
> 
> ```
> 🏗️ Building Service Worker in development mode...
> 
> 💿 Built Service Worker in: 8.599ms
> 👀 Watching for changes in the service worker file...
> ✘ [ERROR] Could not resolve "virtual:entry-sw"
> 
>     node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23:
>       3 │ import * as build from 'virtual:entry-sw';
>         ╵                        ~~~~~~~~~~~~~~~~~~
> 
>   You can mark the path "virtual:entry-sw" as external to exclude
>   it from the bundle, which will remove this error and leave the
>   unresolved path in the bundle.
> ```
> 
> I guess I need to be able to install the same version

Now ik where this error is coming from. You would need to install an older version of worker runtime. Can't remember which, but if you check the npl version tab, I think it was published about 2-3 months ago

**Comment by vahidvdn** [comment]
@ShafSpecs Starting from [2.1.0-dev.1](https://www.npmjs.com/package/@remix-pwa/client/v/2.1.0-dev.1) is possible to install. But getting the error in build time.

My version was `2.0.1` (right one version before `2.1.0-dev.1`), but it's not available on npm (404 error)

**Comment by vahidvdn** [comment]
@ShafSpecs 

ok, first thing is, there is no `2.0.8` at all for `@remix-pwa/client`. Or maybe I misunderstood you.

Second thing is, I guess previous versions should be there for installation. I mean, it's not backward compatibility. I don't want to upgrade `remix-pwa` with old version of remix. I just want to keep my app up & running with the same version that was working before.

I hope it was clear and please let me know if I am missing anything

**Comment by ShafSpecs** [comment]
> @ShafSpecs
> 
> ok, first thing is, there is no `2.0.8` at all for `@remix-pwa/client`. Or maybe I misunderstood you.

I meant for `@remix-pwa/worker-runtime`. The error you get about an absence of a `virtual:entry-sw` is because `virtual:entry-sw` is exposed for Vite. For use with esbuild, you would need to use an older version. `@remix-pwa/client` version doesn't matter at all as it isn't based of vite or esbuild

**Comment by vahidvdn** [comment]
@ShafSpecs oh, sorry. but my worker version is: `"@remix-pwa/worker-runtime": "^2.0.8"`

I guess I found the issue. My client version is: `"@remix-pwa/client": "^2.0.1"`, but the error says there is no version `2.0.2`. I don't know why this happening. Any idea?
