### ISSUE TITLE
Request for Documentation (specifically what remix-pwa does for you on install)

### ISSUE THREAD

**Issue by Brocktho** [remix-pwa/remix-pwa#46]
Background:
I'm really excited about this project cause I already love Remix and want to have an easy way to create a close to native experience. I was able to get a fresh remix-blues stack up and running with remix-pwa, although I had to remove cypress testing from my CI/CD since Electron was giving me issues and  it was just beyond my understanding at this time. 

Issue:
I read as much as I could from the README and the Roadmap but I still have questions on how I could learn some of the under the hood implementations or what APIs are directly touched by remix-pwa. I'd love to be able to help on the project or give better feedback but it's hard to know what remix-pwa does or doesn't do. I mean that in the sense of, I see some code generation happening when using the CLI tool, but I had issues using that same CLI tool on a remix application I already have in production, as a result some features of the library are definitely not working after I tried filling in what I could see from a successful fresh install. 

Request:
1. Adding links to useful documentation or other references that go into more detail of what a PWA requires
2. Adding information surrounding what the CLI tool aims to accomplish and what a user can do to set things up themselves should it fail on an existing application.
3. Possibly looking at implementing remix-pwa on all existing remix stacks (Blues, Indie, Grunge. Most of it seems ready to go, I just personally experienced issues in the CI/CD pipeline when attempting to run the Cypress tests.)
4.  Add to documentation that CLI issues can happen if comments are present in the root.tsx file.

Final Note:
This is a really amazing project and makes Native Application support seem like an achievable goal for anyone with a remix stack already, I'd just love to have extra documentation so I can do something to help the project along and have more confidence in using it on existing applications.

Edit: 
Dug through other issues and found the reason i had CLI issues on an existing project. Comments do seem to break the CLI, removing them all has fixed the issue. Added request 4. as a reuslt.

**Comment by Brocktho** [comment]
I have created a PR to address most of these concerns, or at least get started on them.

**Comment by ShafSpecs** [comment]
Okay, speaking of which I haven't been able to maintain `remix-pwa` thanks to college. I'm close to finishing school so I should be having more time for my projects. I would try to be addressing this in the upcoming weeks 👍. Thx a lot for the assistance

**Comment by ShafSpecs** [comment]
I am contemplating giving `remix-pwa` a separate documentation site so that everything is easily available, and navigating the docs becomes easier
