### ISSUE TITLE
Autodetection issues.

### ISSUE THREAD

**Issue by ShafSpecs** [remix-pwa/remix-pwa#64]
Steps to reproduce: 
- Create a new Remix applicaion
- Do not install dependencies
- Run remix-pwa immediately after

**Expected:**
Should ask you what package manager you prefer

**Comment by dev-afzalansari** [comment]
@ShafSpecs 
> Should ask you what package manager you prefer

Do you mean you want to prompt another question for the preferred package manager when no package manager is used yet?

**Comment by ShafSpecs** [comment]
@dev-afzalansari Yes. Currently, it defaults to yarn an uses `yarn install`, if no lock file is found. It should prompt the user about the package manager
