### ISSUE TITLE
`root.tsx` gets broken when updating `remix-pwa`

### ISSUE THREAD

**Issue by ShafSpecs** [remix-pwa/remix-pwa#72]
Steps to reproduce:
- Have a Remix project
- Have `remix-pwa` installed
- Attempt to update `remix-pwa` to get the newer features
- `root.tsx` gets broken as the content are repeated

Solution:
- A possible one is to check if the SW registration in `root` and use that to apply the contents
- Another more versatile option is to overwrite just the content added into the `root.tsx` and leave the rest of the file. This would be great in cases where `root` content gets updated like in `remix-pwa@1.1.6` where a fix for `defer` breaking in loaders was patched

**Comment by dev-afzalansari** [comment]
@ShafSpecs,

What about creating a custom hook in `utils/client/sw-hooks.ts` maybe called `useSWEffect` so we can abstract away that complex implementation of `postMessage` and the user can have cleaner `root.tsx` and then it will become easy for us to update that hook by just overwriting the content of `utils/client/sw-hooks.ts` with the new content.

**Comment by ShafSpecs** [comment]
> @ShafSpecs,
> 
> What about creating a custom hook in `utils/client/sw-hooks.ts` maybe called `useSWEffect` so we can abstract away that complex implementation of `postMessage` and the user can have cleaner `root.tsx` and then it will become easy for us to update that hook by just overwriting the content of `utils/client/sw-hooks.ts` with the new content.

This would totally work. And would definitely make the root cleaner, all you would need is to declare the hook in root and it won't matter if the implementation change 👍. Currently ill tho, would look at it once I get better 🙏

**Comment by ShafSpecs** [comment]
*Just realised this isn't done*

**Comment by ShafSpecs** [comment]
*Just realised this isn't done. Hook suggestion is a WIP*
