### ISSUE TITLE
Not compatible with Route File Naming (v2)

### ISSUE THREAD

**Issue by skriems** [remix-pwa/remix-pwa#82]
yesterday evening I wanted to take a fresh look on remix (indie stack) and this project (thanks btw 🙂 🎉 ) and found out, that it it not working with the new file based routing system.

I managed my files slightly different, but this would be the correct name for the routes, I guess:
```
app/routes/resources.manifest[.]webmanifest.tsx
app/routes/resources.subscribe.tsx
```

Obviously the paths would also need to be updated in the service worker and the meta tag. I could create a PR but I don't have much time unfortunately and do not know how you would like this to be handled, given that the v2 routing is still behind a _future-flag_

**Comment by ShafSpecs** [comment]
Thanks for pointing this out! I guess an easy (and quick) solution would be to add another prompt when installing `remix-pwa`:
```sh
What file routing convention are you using?
> v1
> v2 (future_flag)
```
Or to read the `remix.config.js` file and detect the convention being used. Tbh, I want to avoid making the prompt too large and the installation process to be quick and smooth.

**Comment by ShafSpecs** [comment]
Update: Currently working on this amongst many others :+1:

**Comment by ShafSpecs** [comment]
v2 prerelease is here and it fixes this as well as many other issues 🥳
