### ISSUE TITLE
useSWEffect breaks an app that requires authentication

### ISSUE THREAD

**Issue by vinmugambi** [remix-pwa/remix-pwa#92]
My application has routes that normally respond with 403/404 error when the visitor is not authenticated.
After adding the `useSWEffect`   hook as directed in the docs, all routes break when no user is authenticated  including the ones that don't require authentication. Here is the error that is caught.

`caught TypeError: Cannot read properties of null (reading 'then')
    at isPromise (useSWEffect.ts:15:43)
    at useSWEffect.ts:36:26
    at Array.filter (<anonymous>)
    at useSWEffect.ts:35:44
    at Array.filter (<anonymous>)
    at useSWEffect.ts:32:28
 `

**Comment by rphlmr** [comment]
https://github.com/remix-pwa/sw/blob/e96fedf840258e8e4470e6b329e6ea3e05340947/src/react/useSWEffect.ts#L15

`isPromise` should checks over `null` because `typeof null === 'object'` is true.

```ts
function isPromise(p) {
        if (p && typeof p === 'object' && typeof p.then === 'function') {
            return true;
        }
        return false;
    }
```
Should solves the error ;)

**Comment by MarianoArg** [comment]
Is this already released? I just checked and the fix isn't in the latest release `v0.3.4`. I'm asking because I'm currently facing this same issue.

**Comment by ShafSpecs** [comment]
> Is this already released? I just checked and the fix isn't in the latest release `v0.3.4`. I'm asking because I'm currently facing this same issue.

Yeah, `0.3.4` isn't the latest release. There are three new versions after including a `v1`

**Comment by MarianoArg** [comment]
> > Is this already released? I just checked and the fix isn't in the latest release `v0.3.4`. I'm asking because I'm currently facing this same issue.
> 
> Yeah, `0.3.4` isn't the latest release. There are three new versions after including a `v1`

Yep, sorry. I was talking about `@remix-pwa/push` which in its latest published version on npm has ` "@remix-pwa/sw": "^0.1.0",` as a peer dependency. So If I manually install the latest sw version I ran into the peer dependencies issue.

**Comment by ShafSpecs** [comment]
For now, the `--force` flag is to be used. The push package is also V1 but npm is giving me trouble publishing it, might just switch it to v1.0.1

**Comment by MarianoArg** [comment]
Oh I see. Ok, thanks for the help!
