### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by DHFW** [remix-pwa/remix-pwa#93]
Hi, I'm using Remix 1.16.1 with the latest packages from @remix-pwa (sw and push) and followed the guids on the docs. But when I do that, I get this unexpected token error when I add the subscribeToPush route.

In remix-config.js I have set this option:
```
serverModuleFormat: 'cjs',
```

And in my package.json I added this 
```
"dev:worker": "esbuild ./app/entry.worker.ts --outfile=./public/entry.worker.js --bundle --format=cjs --define:process.env.NODE_ENV='\"development\"' --watch",
```

I need the cjs format due to other dependencies. But I've tried with esm as format as well.

I get the error on this line:

```@remix-pwa/push/lib/index.js:2
export { subscribeToPush, unsubscribeFromPush } from './client/subscription';
```

Any idea how to fix?

**Comment by ShafSpecs** [comment]
> I get the error on this line:
> 
> ```
> export { subscribeToPush, unsubscribeFromPush } from './client/subscription';
> ```
> 
> Any idea how to fix?

What error do you get?

**Comment by DHFW** [comment]
Thanks for the swift response. The error is in the title :) 
Unexpected token 'export'

**Comment by ShafSpecs** [comment]
Tried replicating but couldn't get the bug to appear. Even with `cjs` format both in my worker script and remix config file

**Comment by DHFW** [comment]
Mmm, ok. I will let you know if I can fix it.

**Comment by DHFW** [comment]
@rphlmr Thanks! That helped so I don't have an error anymore. Now trying to solve the next set or errors.
